# Building image
FROM node:22-alpine AS builder
WORKDIR /app

COPY . .

RUN npm install --workspace=@app/common --workspace=@app/server --legacy-peer-deps

# Building common
RUN npm run common:build

EXPOSE 5000
CMD ["npm", "run", "server:dev"]
